# Site settings
title: Jemcraft
email: hello@jemcraft.co
description: > # this means to ignore newlines until "baseurl:"
  Jemcraft
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jemcraft.co" # the base hostname & protocol for your site
twitter_username: jehosafet
github_username:  Jemcraft

# Build settings
markdown: kramdown
jay_bio: >
    Jay knows how to turn complicated problems into mathematical solutions. He has multiple years of commercial experience applying mathematical optimization to projects with clients such as the Australian national postal service, and the Australian National Broadband Network. In his free time, Jay is a PhD student in machine learning and neural computation at Carnegie Mellon University.
emre_bio: >
    Emre has several years of experience working as a creative professional. His talents including everything from UX design and front-end web development, to motion graphics and illustration. His clients range from larger companies, such as Hewlett Parkard and Microsoft, to startups, film studios, non-profits, and local businesses. In his free time Emre enjoys meditating in his zen garden.
emre_email: emre@jemcraft.co
jay_email: jay@jemcraft.co
group_email: hello@jemcraft.co
