# Site settings
title: Jemcraft
email: hello@jemcraft.co
description: > # this means to ignore newlines until "baseurl:"
  Jemcraft
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jemcraft.co" # the base hostname & protocol for your site
twitter_username: jehosafet
github_username:  Jemcraft

# Build settings
markdown: kramdown
footer_words: Get in touch. Send us an <a href="mailto:hello@jemcraft.co">email</a>.
jay_bio: >
    Jay is a Hennig. Jay is a Hennig. Jay is a Hennig. Jay is a Hennig.
emre_bio: >
    Emre is an Erdener. Emre is an Erdener. Emre is an Erdener.
emre_email: emre@jemcraft.co
jay_email: jay@jemcraft.co
